---
exclude_paths:
 - 'alloyweb/API/angular-auto-complete.js'
 - 'alloyweb/API/autoComplete.js'
 - 'alloyweb/API/cast.framework.js'
 - 'alloyweb/API/cast.v1.js'
 - 'alloyweb/API/jquery.sortable.js'
 - 'chromecast/frontend/api/cast_receiver_framework.js'
 - 'alloyapi/v1/musicbrainz.js'
 - 'alloyapi/v1/simple-lastfm.js'
 - 'alloyapi/music-metadata/**'
 - 'common/export_assets_to_android_ios.jsx'
 - 'common/log-rotator/**'
 - 'common/fast-sass-loader/**'
 - 'alloydroid/Tests/**.*'
 - 'alloy/js/material-dashboard.js'
 - '.vscode/**.*'
 - '*.md'
 - '**/*.md'
 - 'spec/**/*'
 - 'benchmarks/**/*'
 - '*.min.js'
 - '**/tests/**'
 - .*[\.-]min\.css
 - .*[\.-]min\.js
 - .*node_modules/.*
 - .*bower_components
 - .*vendor/.*
 - .*third[_-]?[Pp]arty
 - .*docs?/.*
 - .*samples
 - .*releases?/.*
 - .*builds
 - .*dist/.*
 - .*external
 - .*libs/.*
 - .*d3\.js
 - .*angular(-resource|)?\.js
 - .*select2(-resource|)?\.js
 - .*-ace\.js
 - .*typeahead\.js
 - .*jquery-ui\.js
 - .*reveal\.js
 - .*three\.js
 - .*chart\.js
 - .*jquery\.js
 - .*underscore\.js
 - .*lodash\.js
 - .*bootstrap\.js
 - .*bootstrap\.css
 - .*font-awesome\.css